document.addEventListener("DOMContentLoaded",()=>{
 const S={all:[],shown:[],district:"전체",keyword:"",view:"list",favs:storeGet("busanFavs",[]),recent:storeGet("busanRecent",[]),map:null,markers:[],cluster:null};
 const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
 const E={grid:$("#grid"),empty:$("#empty"),status:$("#status"),count:$("#result-count"),title:$("#result-title"),districts:$("#districts"),listInput:$("#list-input"),heroInput:$("#hero-input"),mapPanel:$("#map-panel"),mapGuide:$("#map-guide"),favGrid:$("#fav-grid"),favEmpty:$("#fav-empty"),favCount:$("#fav-count"),recent:$("#recent"),recentList:$("#recent-list"),modal:$("#modal"),detail:$("#detail-content"),toast:$("#toast")};
 bind(); init();
 async function init(){status("부산 맛집 정보를 불러오는 중이에요…");try{S.all=await loadData();console.log("부산 맛집 API 데이터:",S.all);status("")}catch(err){console.error("API 오류:",err);S.all=normalize(SAMPLE_RESTAURANTS);status("공공데이터 연결에 실패해 샘플 데이터를 표시합니다.")}S.shown=[...S.all];renderDistricts();renderAll();renderRecent()}
 async function loadData(){const key=APP_CONFIG.BUSAN_DATA_API_KEY;if(APP_CONFIG.USE_SAMPLE_DATA||!key||key.includes("여기에_"))return normalize(SAMPLE_RESTAURANTS);const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),9000);const url=`${APP_CONFIG.API_BASE_URL}?serviceKey=${key}&numOfRows=100&pageNo=1&resultType=json`;const res=await fetch(url,{signal:ctrl.signal});clearTimeout(timer);if(!res.ok)throw Error(`HTTP ${res.status}`);const data=await res.json();const code=data?.getFoodKr?.header?.resultCode||data?.response?.header?.resultCode||data?.header?.resultCode;if(code&&code!=="00")throw Error(`API 코드 ${code}`);const items=data?.getFoodKr?.item||data?.response?.body?.items?.item||data?.body?.items?.item||data?.items||[];if(!Array.isArray(items)||!items.length)throw Error("데이터 없음");return normalize(items)}
 function normalize(items){return items.map((x,i)=>({...x,UC_SEQ:String(x.UC_SEQ||i),MAIN_TITLE:clean(x.MAIN_TITLE||x.PLACE||"이름 없는 맛집"),GUGUN_NM:clean(x.GUGUN_NM||"지역 미상"),ADDR1:clean(x.ADDR1),ADDR2:clean(x.ADDR2),CNTCT_TEL:clean(x.CNTCT_TEL),RPRSNTV_MENU:clean(x.RPRSNTV_MENU),USAGE_DAY_WEEK_AND_TIME:clean(x.USAGE_DAY_WEEK_AND_TIME),TITLE:clean(x.TITLE),ITEMCNTNTS:clean(x.ITEMCNTNTS),HOMEPAGE_URL:safeUrl(x.HOMEPAGE_URL),image:imageUrl(x.MAIN_IMG_THUMB||x.MAIN_IMG_NORMAL),LAT:Number(x.LAT),LNG:Number(x.LNG)}))}
 function clean(v=""){const t=document.createElement("textarea");t.innerHTML=String(v).trim();return t.value.replace(/\s+/g," ")}function safeUrl(v=""){v=String(v).trim();return/^https?:\/\//i.test(v)?v:""}function imageUrl(v=""){v=String(v).replace(/^>/,"").trim();if(/^https?:\/\//i.test(v))return v;if(v.startsWith("/"))return APP_CONFIG.IMAGE_BASE_URL+v;return SAMPLE_RESTAURANTS[0].MAIN_IMG_THUMB}
 function bind(){$("#hero-form").addEventListener("submit",e=>{e.preventDefault();S.keyword=E.heroInput.value.trim();E.listInput.value=S.keyword;filter();navigate("explore")});E.listInput.addEventListener("input",debounce(e=>{S.keyword=e.target.value.trim();E.heroInput.value=S.keyword;filter()},180));$("#reset").onclick=reset;$("[data-reset]").onclick=reset;$$('[data-nav]').forEach(b=>b.addEventListener("click",()=>navigate(b.dataset.nav)));$$('[data-view]').forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view)));$("#clear-favs").onclick=()=>{if(!S.favs.length||confirm("찜한 맛집을 모두 삭제할까요?")){S.favs=[];saveFavs();renderAll();renderFavs();toast("찜 목록을 비웠어요.")}};$("#map-retry").onclick=loadMap;$$('[data-close]').forEach(x=>x.onclick=closeDetail);document.addEventListener("keydown",e=>{if(e.key==="Escape")closeDetail()})}
 function filter(){const key=S.keyword.toLowerCase();S.shown=S.all.filter(x=>{const district=S.district==="전체"||x.GUGUN_NM===S.district;const text=[x.MAIN_TITLE,x.TITLE,x.RPRSNTV_MENU,x.ADDR1].join(" ").toLowerCase();return district&&(!key||text.includes(key))});renderDistricts();renderAll()}
 function reset(){S.district="전체";S.keyword="";E.listInput.value=E.heroInput.value="";filter()}
 function renderDistricts(){const names=["전체",...new Set(S.all.map(x=>x.GUGUN_NM))];E.districts.innerHTML=names.map(n=>`<button class="chip ${n===S.district?"active":""}" data-district="${esc(n)}">${esc(n)}</button>`).join("");E.districts.querySelectorAll("button").forEach(b=>b.onclick=()=>{S.district=b.dataset.district;filter();navigate("explore")})}
 function renderAll(){cards(E.grid,S.shown);E.count.textContent=`${S.shown.length}곳`;E.title.textContent=S.district!=="전체"?`${S.district} 추천 맛집`:S.keyword?`“${S.keyword}” 검색 결과`:"부산 추천 맛집";E.empty.hidden=!!S.shown.length;E.grid.hidden=!S.shown.length||S.view==="map";E.favCount.textContent=S.favs.length;if(S.view==="map")renderMarkers()}
 function cards(target,items){target.innerHTML=items.map(x=>`<article class="card"><div class="card-img"><img src="${attr(x.image)}" alt="${attr(x.MAIN_TITLE)} 대표 이미지" loading="lazy"><span class="tag">${esc(x.GUGUN_NM)}</span><button class="heart ${isFav(x.UC_SEQ)?"active":""}" data-fav="${x.UC_SEQ}" aria-label="${attr(x.MAIN_TITLE)} 찜하기">${isFav(x.UC_SEQ)?"♥":"♡"}</button></div><div class="card-body"><h3>${esc(x.MAIN_TITLE)}</h3><p class="subtitle">${esc(x.TITLE||x.ITEMCNTNTS.slice(0,55)||"부산 추천 맛집")}</p><ul class="meta"><li><b>대표메뉴</b><span>${esc(x.RPRSNTV_MENU||"정보 없음")}</span></li><li><b>운영시간</b><span>${esc(x.USAGE_DAY_WEEK_AND_TIME||"방문 전 확인")}</span></li></ul><button class="detail-btn" data-detail="${x.UC_SEQ}">자세히 보기</button></div></article>`).join("");target.querySelectorAll("[data-fav]").forEach(b=>b.onclick=()=>toggleFav(b.dataset.fav));target.querySelectorAll("[data-detail]").forEach(b=>b.onclick=()=>openDetail(b.dataset.detail))}
 function openDetail(id){const x=S.all.find(v=>v.UC_SEQ===String(id));if(!x)return;addRecent(id);const tel=x.CNTCT_TEL.replace(/[^0-9+\-]/g,"");const map=coords(x)?`https://map.kakao.com/link/map/${encodeURIComponent(x.MAIN_TITLE)},${x.LAT},${x.LNG}`:"",route=coords(x)?`https://map.kakao.com/link/to/${encodeURIComponent(x.MAIN_TITLE)},${x.LAT},${x.LNG}`:"";E.detail.innerHTML=`<div class="detail-hero"><img src="${attr(x.image)}" alt="${attr(x.MAIN_TITLE)}"><div class="detail-title"><small>${esc(x.GUGUN_NM)} · ${esc(x.RPRSNTV_MENU||"부산 추천 맛집")}</small><h2 id="detail-title">${esc(x.MAIN_TITLE)}</h2></div></div><div class="detail-body"><p>${esc(x.ITEMCNTNTS||x.TITLE||"상세 소개가 준비 중입니다.")}</p><div class="info"><div><small>주소</small><b>${esc([x.ADDR1,x.ADDR2].filter(Boolean).join(" ")||"정보 없음")}</b></div><div><small>운영시간</small><b>${esc(x.USAGE_DAY_WEEK_AND_TIME||"방문 전 확인")}</b></div><div><small>대표메뉴</small><b>${esc(x.RPRSNTV_MENU||"정보 없음")}</b></div><div><small>전화번호</small><b>${esc(x.CNTCT_TEL||"정보 없음")}</b></div></div><div class="actions">${tel?`<a class="primary" href="tel:${attr(tel)}">전화하기</a>`:""}<button data-copy>주소 복사</button>${x.HOMEPAGE_URL?`<a href="${attr(x.HOMEPAGE_URL)}" target="_blank" rel="noopener">홈페이지</a>`:""}${map?`<a href="${attr(map)}" target="_blank" rel="noopener">지도 보기</a><a href="${attr(route)}" target="_blank" rel="noopener">길찾기</a>`:""}<button data-modal-fav>${isFav(id)?"♥ 찜 해제":"♡ 찜하기"}</button></div><p class="notice">부산광역시 공공데이터 기반 정보입니다. 실제 영업시간과 메뉴는 방문 전 확인해 주세요.</p></div>`;E.detail.querySelector("[data-copy]").onclick=async()=>{await navigator.clipboard.writeText([x.ADDR1,x.ADDR2].filter(Boolean).join(" "));toast("주소를 복사했어요.")};E.detail.querySelector("[data-modal-fav]").onclick=()=>{toggleFav(id);closeDetail();openDetail(id)};E.modal.hidden=false;document.body.style.overflow="hidden";setTimeout(()=>$(".close").focus(),10)}
 function closeDetail(){E.modal.hidden=true;document.body.style.overflow=""}function isFav(id){return S.favs.includes(String(id))}function toggleFav(id){id=String(id);S.favs=isFav(id)?S.favs.filter(v=>v!==id):[id,...S.favs];saveFavs();renderAll();renderFavs();toast(isFav(id)?"찜한 맛집에 저장했어요.":"찜에서 삭제했어요.")}function saveFavs(){localStorage.setItem("busanFavs",JSON.stringify(S.favs))}
 function renderFavs(){const items=S.favs.map(id=>S.all.find(x=>x.UC_SEQ===id)).filter(Boolean);cards(E.favGrid,items);E.favEmpty.hidden=!!items.length;E.favGrid.hidden=!items.length;E.favCount.textContent=S.favs.length}function addRecent(id){S.recent=[String(id),...S.recent.filter(v=>v!==String(id))].slice(0,10);localStorage.setItem("busanRecent",JSON.stringify(S.recent));renderRecent()}function renderRecent(){const items=S.recent.map(id=>S.all.find(x=>x.UC_SEQ===id)).filter(Boolean);E.recent.hidden=!items.length;E.recentList.innerHTML=items.map(x=>`<button class="recent-card" data-recent="${x.UC_SEQ}"><img src="${attr(x.image)}" alt=""><span><b>${esc(x.MAIN_TITLE)}</b><small>${esc(x.GUGUN_NM)} · ${esc(x.RPRSNTV_MENU||"추천 맛집")}</small></span></button>`).join("");E.recentList.querySelectorAll("button").forEach(b=>b.onclick=()=>openDetail(b.dataset.recent))}
 function navigate(to){$$('[data-nav]').forEach(b=>b.classList.toggle("active",b.dataset.nav===to));$("#favorites").hidden=to!=="favorites";if(to==="home")scrollTo({top:0,behavior:"smooth"});if(to==="explore"){switchView("list");$("#explore").scrollIntoView({behavior:"smooth"})}if(to==="map"){switchView("map");$("#explore").scrollIntoView({behavior:"smooth"})}if(to==="favorites"){renderFavs();$("#favorites").scrollIntoView({behavior:"smooth"})}}
 function switchView(view){S.view=view;$$('[data-view]').forEach(b=>b.classList.toggle("active",b.dataset.view===view));E.grid.hidden=view==="map"||!S.shown.length;E.mapPanel.hidden=view!=="map";if(view==="map")loadMap()}
 function loadMap(){const key=APP_CONFIG.KAKAO_JAVASCRIPT_KEY;if(!key||key.includes("여기에_")){E.mapGuide.hidden=false;return}if(window.kakao?.maps)return kakao.maps.load(initMap);document.querySelector("script[data-map]")?.remove();const s=document.createElement("script");s.dataset.map="1";s.src=`https://dapi.kakao.com/v2/maps/sdk.js?appkey=${key}&autoload=false&libraries=clusterer`;s.onload=()=>kakao.maps.load(initMap);s.onerror=()=>{E.mapGuide.hidden=false;E.mapGuide.querySelector("h3").textContent="지도를 불러오지 못했어요";E.mapGuide.querySelector("p").textContent="API 키와 JavaScript SDK 도메인을 확인해 주세요."};document.head.appendChild(s)}
 function initMap(){E.mapGuide.hidden=true;if(!S.map){S.map=new kakao.maps.Map($("#kakao-map"),{center:new kakao.maps.LatLng(35.1796,129.0756),level:8});S.cluster=new kakao.maps.MarkerClusterer({map:S.map,averageCenter:true,minLevel:7})}renderMarkers();setTimeout(()=>S.map.relayout(),50)}function renderMarkers(){if(!S.map||!window.kakao?.maps)return;S.cluster.clear();S.markers=S.shown.filter(coords).map(x=>{const m=new kakao.maps.Marker({position:new kakao.maps.LatLng(x.LAT,x.LNG),title:x.MAIN_TITLE});const info=new kakao.maps.InfoWindow({content:`<div style="padding:10px;min-width:170px;font-size:12px"><b style="color:#0877b9">${esc(x.MAIN_TITLE)}</b><br>${esc(x.ADDR1)}</div>`});kakao.maps.event.addListener(m,"click",()=>info.open(S.map,m));return m});S.cluster.addMarkers(S.markers)}function coords(x){return Number.isFinite(x.LAT)&&Number.isFinite(x.LNG)&&x.LAT>34&&x.LAT<36&&x.LNG>128&&x.LNG<130}
 function status(msg){E.status.hidden=!msg;E.status.textContent=msg}function toast(msg){E.toast.textContent=msg;E.toast.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove("show"),1800)}function storeGet(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}function debounce(fn,ms){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}function esc(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}function attr(v=""){return esc(v)}
});
