/* 부산 맛집 앱 UI 다국어 사전: 식당 고유명·주소·메뉴는 공공데이터 원문 유지 */
const I18N=(()=>{
  const messages={
    ko:{brand:"부산의 한 끼",home:"홈",explore:"맛집 탐색",map:"지도",favorites:"찜한 맛집",heroTitle:"부산에서 만나는<br><em>오늘의 좋은 한 끼</em>",heroText:"부산시가 추천하는 맛집을 지역과 메뉴로 찾아보고,<br>지도에서 위치까지 한눈에 확인해 보세요.",heroPlaceholder:"먹고 싶은 메뉴나 맛집을 검색해 보세요",search:"맛집 찾기",areaTitle:"어느 동네에서 드실래요?",areaText:"부산의 구·군을 선택하면 해당 지역 맛집만 모아볼 수 있어요.",listTitle:"맛집 목록",listHelp:"선택하면 지도에서 바로 보여요",scroll:"아래로 스크롤해 더 많은 맛집 보기",more:"추천 맛집 더보기",compare:"사진과 메뉴를 비교해 보세요",reset:"필터 초기화",filterPlaceholder:"맛집명, 메뉴, 주소 검색",all:"전체",placeUnit:"곳",recommended:"부산 추천 맛집",areaRecommended:"추천 맛집",results:"검색 결과",address:"주소",menu:"메뉴",hours:"운영시간",phone:"전화번호",noInfo:"정보 없음",checkBefore:"방문 전 확인",details:"자세히 보기",call:"전화하기",copy:"주소 복사",homepage:"홈페이지",viewMap:"지도 보기",route:"길찾기",favorite:"찜하기",unfavorite:"찜 해제",recent:"최근 본 맛집",empty:"조건에 맞는 맛집이 없어요",emptyHelp:"검색어나 지역을 바꿔 다시 찾아보세요.",showAll:"전체 맛집 보기",mobileExplore:"탐색",mobileFav:"찜",language:"언어 선택",mapHint:"마커 숫자를 누르거나 지도를 확대해 보세요"},
    en:{brand:"A Bite of Busan",home:"Home",explore:"Restaurants",map:"Map",favorites:"Favorites",heroTitle:"Discover Busan<br><em>One delicious bite at a time</em>",heroText:"Find Busan-recommended restaurants by area and menu,<br>then check every location on the map.",heroPlaceholder:"Search restaurants or menus",search:"Find food",areaTitle:"Which neighborhood?",areaText:"Choose a district to browse restaurants in that area.",listTitle:"Restaurant list",listHelp:"Select one to locate it on the map",scroll:"Scroll down to see more restaurants",more:"More recommendations",compare:"Compare photos and menus",reset:"Reset filters",filterPlaceholder:"Search name, menu, or address",all:"All",placeUnit:" places",recommended:"Busan restaurants",areaRecommended:"recommended restaurants",results:"Search results",address:"Address",menu:"Menu",hours:"Hours",phone:"Phone",noInfo:"No information",checkBefore:"Check before visiting",details:"View details",call:"Call",copy:"Copy address",homepage:"Website",viewMap:"View map",route:"Directions",favorite:"Favorite",unfavorite:"Remove favorite",recent:"Recently viewed",empty:"No restaurants found",emptyHelp:"Try another keyword or district.",showAll:"View all restaurants",mobileExplore:"Explore",mobileFav:"Saved",language:"Select language",mapHint:"Tap a cluster or zoom in to see restaurants"},
    ja:{brand:"釜山のひと皿",home:"ホーム",explore:"グルメ検索",map:"地図",favorites:"お気に入り",heroTitle:"釜山で出会う<br><em>今日のおいしい一食</em>",heroText:"釜山市おすすめのお店を地域やメニューから探し、<br>地図で場所を確認できます。",heroPlaceholder:"店名やメニューを検索",search:"お店を探す",areaTitle:"どのエリアで食べますか？",areaText:"釜山の区・郡を選ぶと、その地域のお店を表示します。",listTitle:"お店一覧",listHelp:"選択すると地図に表示されます",scroll:"下へスクロールしてもっと見る",more:"おすすめをもっと見る",compare:"写真とメニューを比較",reset:"絞り込み解除",filterPlaceholder:"店名・メニュー・住所を検索",all:"すべて",placeUnit:"店",recommended:"釜山おすすめグルメ",areaRecommended:"おすすめグルメ",results:"検索結果",address:"住所",menu:"メニュー",hours:"営業時間",phone:"電話番号",noInfo:"情報なし",checkBefore:"来店前に確認",details:"詳細を見る",call:"電話する",copy:"住所をコピー",homepage:"ホームページ",viewMap:"地図を見る",route:"経路案内",favorite:"お気に入り",unfavorite:"お気に入り解除",recent:"最近見たお店",empty:"該当するお店がありません",emptyHelp:"検索語や地域を変更してください。",showAll:"すべてのお店を見る",mobileExplore:"検索",mobileFav:"保存",language:"言語選択",mapHint:"数字のマーカーをタップ、または地図を拡大してください"},
    zh:{brand:"釜山一餐",home:"首页",explore:"美食探索",map:"地图",favorites:"收藏",heroTitle:"在釜山遇见<br><em>今天的美味一餐</em>",heroText:"按地区和菜单查找釜山市推荐餐厅，<br>并在地图上一览位置。",heroPlaceholder:"搜索餐厅或菜单",search:"查找美食",areaTitle:"想在哪个地区用餐？",areaText:"选择釜山的区或郡，查看当地餐厅。",listTitle:"餐厅列表",listHelp:"选择后可在地图中查看",scroll:"向下滚动查看更多餐厅",more:"查看更多推荐",compare:"比较照片和菜单",reset:"重置筛选",filterPlaceholder:"搜索餐厅、菜单或地址",all:"全部",placeUnit:"家",recommended:"釜山推荐餐厅",areaRecommended:"推荐餐厅",results:"搜索结果",address:"地址",menu:"菜单",hours:"营业时间",phone:"电话",noInfo:"暂无信息",checkBefore:"到访前请确认",details:"查看详情",call:"拨打电话",copy:"复制地址",homepage:"官方网站",viewMap:"查看地图",route:"路线",favorite:"收藏",unfavorite:"取消收藏",recent:"最近浏览",empty:"没有符合条件的餐厅",emptyHelp:"请更换关键词或地区。",showAll:"查看全部餐厅",mobileExplore:"探索",mobileFav:"收藏",language:"选择语言",mapHint:"点击数字标记或放大地图查看餐厅"}
  };
  const districtNames={
    en:{강서구:"Gangseo-gu",금정구:"Geumjeong-gu",기장군:"Gijang-gun",남구:"Nam-gu",동구:"Dong-gu",동래구:"Dongnae-gu",부산진구:"Busanjin-gu",북구:"Buk-gu",사상구:"Sasang-gu",사하구:"Saha-gu",서구:"Seo-gu",수영구:"Suyeong-gu",연제구:"Yeonje-gu",영도구:"Yeongdo-gu",중구:"Jung-gu",해운대구:"Haeundae-gu"},
    ja:{강서구:"江西区",금정구:"金井区",기장군:"機張郡",남구:"南区",동구:"東区",동래구:"東莱区",부산진구:"釜山鎮区",북구:"北区",사상구:"沙上区",사하구:"沙下区",서구:"西区",수영구:"水営区",연제구:"蓮堤区",영도구:"影島区",중구:"中区",해운대구:"海雲台区"},
    zh:{강서구:"江西区",금정구:"金井区",기장군:"机张郡",남구:"南区",동구:"东区",동래구:"东莱区",부산진구:"釜山镇区",북구:"北区",사상구:"沙上区",사하구:"沙下区",서구:"西区",수영구:"水营区",연제구:"莲堤区",영도구:"影岛区",중구:"中区",해운대구:"海云台区"}
  };
  let lang="ko";
  const t=key=>messages[lang]?.[key]||messages.ko[key]||key;
  const setText=(selector,key,html=false)=>{const el=document.querySelector(selector);if(el)el[html?"innerHTML":"textContent"]=t(key)};
  function apply(){document.documentElement.lang=lang;setText(".brand>span:last-child>b","brand");setText(".hero h1","heroTitle",true);setText(".hero p","heroText",true);setText("#hero-form button","search");setText(".districts .heading h2","areaTitle");setText(".districts .heading p","areaText");setText(".map-list-head b","listTitle");setText(".map-list-head small","listHelp");setText(".scroll-guide","scroll");setText(".more-title h3","more");setText(".more-title span","compare");setText("#reset","reset");setText("#empty h3","empty");setText("#empty p","emptyHelp");setText("#empty button","showAll");setText("#recent h2","recent");document.querySelectorAll('[data-i18n="home"]').forEach(x=>x.textContent=t("home"));document.querySelectorAll('[data-i18n="explore"]').forEach(x=>x.textContent=t("explore"));document.querySelectorAll('[data-i18n="map"]').forEach(x=>x.textContent=t("map"));document.querySelectorAll('[data-i18n="favorites"]').forEach(x=>x.textContent=t("favorites"));const hero=document.querySelector("#hero-input"),list=document.querySelector("#list-input"),select=document.querySelector("#language-select");if(hero)hero.placeholder=t("heroPlaceholder");if(list)list.placeholder=t("filterPlaceholder");if(select){select.value=lang;select.setAttribute("aria-label",t("language"))}document.body.dataset.lang=lang;document.body.style.setProperty("--map-hint",`"${t("mapHint")}"`)}
  function set(next){lang=messages[next]?next:"ko";localStorage.setItem("busanLanguage",lang);apply()}
  function init(){lang=localStorage.getItem("busanLanguage")||"ko";apply()}
  const district=name=>name==="전체"?t("all"):(districtNames[lang]?.[name]||name);
  return{t,district,set,init,get lang(){return lang}};
})();
